#!/bin/bash

rm SConstruct
rm Makefile
rm *.dev
rm *.vcproj
rm *.vcxproj
rm *.sln
rm *.filters
rm *.cbp
rm *.txt
rm *.rc
rm *.aps

rm C3DSMeshFileLoader.cpp
rm C3DSMeshFileLoader.h
rm CAnimatedMeshHalfLife.cpp
rm CAnimatedMeshHalfLife.h
rm CAnimatedMeshMD2.cpp
rm CAnimatedMeshMD2.h
rm CAnimatedMeshMD3.cpp
rm CAnimatedMeshMD3.h
rm CB3DMeshFileLoader.cpp
rm CB3DMeshFileLoader.h
rm CBSPMeshFileLoader.cpp
rm CBSPMeshFileLoader.h
rm CCgMaterialRenderer.cpp
rm CCgMaterialRenderer.h
rm CColladaFileLoader.cpp
rm CColladaFileLoader.h
rm CColladaMeshWriter.cpp
rm CColladaMeshWriter.h
rm CCSMLoader.cpp
rm CCSMLoader.h
rm CD3D8Driver.cpp
rm CD3D8Driver.h
rm CD3D8MaterialRenderer.h
rm CD3D8NormalMapRenderer.cpp
rm CD3D8NormalMapRenderer.h
rm CD3D8ParallaxMapRenderer.cpp
rm CD3D8ParallaxMapRenderer.h
rm CD3D8ShaderMaterialRenderer.cpp
rm CD3D8ShaderMaterialRenderer.h
rm CD3D8Texture.cpp
rm CD3D8Texture.h
rm CD3D9CgMaterialRenderer.cpp
rm CD3D9CgMaterialRenderer.h
rm CD3D9Driver.cpp
rm CD3D9Driver.h
rm CD3D9HLSLMaterialRenderer.cpp
rm CD3D9HLSLMaterialRenderer.h
rm CD3D9MaterialRenderer.h
rm CD3D9NormalMapRenderer.cpp
rm CD3D9NormalMapRenderer.h
rm CD3D9ParallaxMapRenderer.cpp
rm CD3D9ParallaxMapRenderer.h
rm CD3D9ShaderMaterialRenderer.cpp
rm CD3D9ShaderMaterialRenderer.h
rm CD3D9Texture.cpp
rm CD3D9Texture.h
rm CDMFLoader.cpp
rm CDMFLoader.h
rm CImageLoaderBMP.cpp
rm CImageLoaderBMP.h
rm CImageLoaderDDS.cpp
rm CImageLoaderDDS.h
rm CImageLoaderPCX.cpp
rm CImageLoaderPCX.h
rm CImageLoaderPPM.cpp
rm CImageLoaderPPM.h
rm CImageLoaderPSD.cpp
rm CImageLoaderPSD.h
rm CImageLoaderRGB.cpp
rm CImageLoaderRGB.h
rm CImageLoaderTGA.cpp
rm CImageLoaderTGA.h
rm CImageLoaderWAL.cpp
rm CImageLoaderWAL.h
rm CImageWriterBMP.cpp
rm CImageWriterBMP.h
rm CImageWriterPCX.cpp
rm CImageWriterPCX.h
rm CImageWriterPNG.cpp
rm CImageWriterPNG.h
rm CImageWriterPPM.cpp
rm CImageWriterPPM.h
rm CImageWriterPSD.cpp
rm CImageWriterPSD.h
rm CImageWriterTGA.cpp
rm CImageWriterTGA.h
rm CIrrDeviceConsole.cpp
rm CIrrDeviceConsole.h
rm CIrrDeviceFB.cpp
rm CIrrDeviceFB.h
rm CIrrDeviceWin32.cpp
rm CIrrDeviceWin32.h
rm CIrrDeviceWinCE.cpp
rm CIrrDeviceWinCE.h
rm CIrrMeshWriter.cpp
rm CIrrMeshWriter.h
rm CLMTSMeshFileLoader.cpp
rm CLMTSMeshFileLoader.h
rm CLWOMeshFileLoader.cpp
rm CLWOMeshFileLoader.h
rm CMD2MeshFileLoader.cpp
rm CMD2MeshFileLoader.h
rm CMD3MeshFileLoader.cpp
rm CMD3MeshFileLoader.h
rm CMountPointReader.cpp
rm CMountPointReader.h
rm CMS3DMeshFileLoader.cpp
rm CMS3DMeshFileLoader.h
rm CMY3DHelper.h
rm CMY3DMeshFileLoader.cpp
rm CMY3DMeshFileLoader.h
rm CNPKReader.cpp
rm CNPKReader.h
rm COBJMeshFileLoader.cpp
rm COBJMeshFileLoader.h
rm COBJMeshWriter.cpp
rm COBJMeshWriter.h
rm COCTLoader.cpp
rm COCTLoader.h
rm COgreMeshFileLoader.cpp
rm COgreMeshFileLoader.h
rm COpenGLCgMaterialRenderer.cpp
rm COpenGLCgMaterialRenderer.h
rm CPakReader.cpp
rm CPakReader.h
rm CPLYMeshFileLoader.cpp
rm CPLYMeshFileLoader.h
rm CPLYMeshWriter.cpp
rm CPLYMeshWriter.h
rm CQ3LevelMesh.cpp
rm CQ3LevelMesh.h
rm CQuake3ShaderSceneNode.cpp
rm CQuake3ShaderSceneNode.h
rm CSMFMeshFileLoader.cpp
rm CSMFMeshFileLoader.h
rm CSoftware2MaterialRenderer.h
rm CSoftwareDriver.cpp
rm CSoftwareDriver.h
rm CSoftwareDriver2.cpp
rm CSoftwareDriver2.h
rm CSoftwareTexture.cpp
rm CSoftwareTexture.h
rm CSTLMeshFileLoader.cpp
rm CSTLMeshFileLoader.h
rm CSTLMeshWriter.cpp
rm CSTLMeshWriter.h
rm CTarReader.cpp
rm CTarReader.h
rm CWADReader.cpp
rm CWADReader.h
rm CXMeshFileLoader.cpp
rm CXMeshFileLoader.h
rm CZipReader.cpp
rm CZipReader.h
